config/routes.rb
Rails.application.routes.draw do

  resources :calendar_requests

  resources :bookings
  
  resources :charges

  resources :calendars

  resources :tour_prices

  resources :tour_cities

  resources :tour_guides

  devise_for :users, :path_prefix => 'my', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  # This must go after devise_for to avoid conflicts
  
  resources :tickets
  
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/faq"
  get "welcome/admin"
  get "welcome/guide"
  
  resources :tours do 
    collection { post :import}
  end

  root to: 'welcome#index'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def index
    if params[:start].present?
    time_range = (Date.strptime(params[:start], '%m/%d/%Y') - 1.day)..(Date.strptime(params[:end], '%m/%d/%Y') + 1.day)
    end

    if params[:search_location].blank?
      if params[:start].blank?
        @tours = Tour.search(params[:search]).order("created_at DESC")
      else
        @tours = Tour.search(params[:search]).order("created_at DESC").joins(:calendars).where(calendars: {calendar_datetime: time_range}) 
      end
    elsif
      if params[:start].blank?
        @tours = Tour.near(params[:search_location], 50).search(params[:search]).order("created_at DESC")
      else
        @tours = Tour.near(params[:search_location], 50).search(params[:search]).order("created_at DESC").joins(:calendars).where(calendars: {calendar_datetime: time_range}) 
      end
    else
      @tours = Tour.all
    end
    
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_how_modal.erb
<div class="modal fade" id="how" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class='modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <br>
      </div>
      <div class="modal-body">
        <div class='container' id='how'>
<!--           <div class='col-md-5'>
            <img alt="Logo" src="/assets/discover.png" height= '200' width='300'/>
          </div> -->
          <div class='col-md-12'>
            <h2>Discover amazing things all around you</h2>
            <br>
            <h4>Querla is a place where you can find walking tours hosted by local people, or you can sign up to host a tour yourself. Our tours are very diverse, including architecture, gardens, local communities and much more. Ever wondered about that old warehouse down the street and what it was used for? Maybe now you can find out.</h4>
            <br>

            <h4>Querla Tours are suitable for tourists who want to get off the beaten track, but also for local people who are interested to discover something new about their neighborhood. Our guides are people who have a passion and want to share it.</h4>
            <br>

            <h4>To come on a tour, simply browse our listings on this site, find a suitable date and sign up! If you can’t find a date that suits you, let us know. To host a tour, fill in the contact form and tell us what you’re interested in.</h4>
            <br>
            <br>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/welcome/_sign_in_modal.html.erb
<div class="modal fade" id="sign_in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Log In</h4>
      </div>
      <div class="modal-body">
            <%= bootstrap_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                    <%= f.email_field :email, :autofocus => true %>
                    <%= f.password_field :password %>
                    <% if devise_mapping.rememberable? -%>
                        <%= f.check_box :remember_me %>
                    <% end %>    
                    <%= f.submit "Log in", :class => 'btn btn-block button_pink' %>
            <% end %>
            <br>
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
            <%= link_to "Forgot password?", new_password_path(resource_name) %><br />
            <% end -%>
            <hr>
            <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-social btn-block btn-facebook" do %>
                <i class="fa fa-facebook"></i>
                Log in with Facebook
            <% end %>
            <br>
            <%= link_to user_omniauth_authorize_path(:google_oauth2), class: "btn btn-social btn-block btn-google-plus" do %>
                <i class="fa fa-google-plus"></i>
                Log in with Google
            <% end %>
            <hr>
            Don't have an account?
                <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                <%= link_to "Sign up", new_registration_path(resource_name) %><br />
            <% end -%>
        </div>

    </div>
  </div>
</div>
  

app/views/welcome/about.html.erb
<div class='container-fluid'>

<div class='col-md-1'>
  </div>
  
  <div class='col-md-10'>
    <div class='row'>
      <h2>About Us</h2>
    </div>
    <div class='row'>
      <p>Querla was founded in 2015 and is based in London UK.</p>  
      <br>
      <p>For curious minded people, Querla is a new way to discover neighbourhoods and hear stories that don't typically get attention. All our guides are local people with a passion that they want to share. Come away with a warm feeling and a sense of having discovered something wonderful.</p>
    </div>
  </div>
  
  <div class='col-md-1'>
  </div>
                         


</div>

app/views/welcome/admin.html.erb
<h3>Administration Links</h3>
<ul class="nav nav-pills nav-stacked">
  <li><%= link_to "Booking", bookings_path %></li>
  <li><%= link_to "Calendar", calendars_path %></li>
  <li><%= link_to "Tours", tours_path %></li>
  <li><%= link_to "Tour Guides", tour_guides_path %></li>
  <li><%= link_to "Pricing Model", tour_prices_path%></li>
  <li><%= link_to "Cities", tour_cities_path%></li>
  <li><%= link_to "Users", users_path%></li>
  <li><%= link_to "Calendar Requests", calendar_requests_path%></li>
</ul>

app/views/welcome/contact.html.erb
<%= render 'tickets/form' %>

app/views/welcome/faq.html.erb
<div class='container'>
  <div class='row'>
    <h1>Frequently Asked Questions</h1>
  </div>
  
  
</div>

app/views/welcome/guide.html.erb
<div class='container'>


    <div class="row">
        <div class='col-md-4'></div>
        <div class='col-md-4'>
          <h2>Thanks for your interest in hosting a tour</h2>
          <h3>Tell us a bit about yourself!</h3>
          <h2></h2>
          <p>* All fields required</p>
          <br>
          <div class="panel panel-info">
            <div class="panel-body">
                <%= render 'tickets/form' %>
            </div>
          </div>
        </div>
    </div>
  
</div>

app/views/welcome/index.html.erb
<div class="container fluid">
  <div class="row header-panel">
    
    <div class='row button-panel'>
        <%= link_to welcome_guide_path do %>
        <div class="btn button_left">
              <h4>Host a Tour</h4>
        </div>
        <% end %>

        <%= link_to "#how", "data-toggle" => "modal" do %>
        <div class="btn button_right">
          <h4>How it Works</h4>
        </div>
        <% end %>
    </div>
    
    <div class='row title'>
      <h1>Walking tours,</h1>
      <h1>for curious people</h1>
    </div>

    <div class="row search-panel">
      <div class='search-panel-wrapper'>
        <%= form_tag welcome_index_path, method: :get, :class => "navbar-form" do %>
        <div class='input-placeholder-group'>
          <div class='input-group'>
            <%= text_field_tag :search, params[:search], class: 'form-control', :placeholder => "What interests you?" %>
          </div><!-- input-group -->
        </div><!-- input-placeholder-group -->
        <div class='input-placeholder-group'>
          <div class='input-group'>
            <%= text_field_tag :search_location, params[:search_location], class: 'form-control', :placeholder => "Location" %>
          </div><!-- input-group -->
        </div><!-- input-placeholder-group -->
        <div class='input-placeholder-group'>
          <div class="input-daterange input-group input-contrast" id="datepicker">
            <!--           <input type="text" class="input-sm form-control" name="start" /> -->
            <%= text_field_tag :start,  params[:start], class: 'input form-control', placeholder: "From"%>
            <span class="input-group-addon">to</span>
            <%= text_field_tag :end,  params[:start], class: 'input form-control', placeholder: "To"%>
          </div><!-- input-daterange input-group input-contrast -->
        </div><!-- input-placeholder-group -->
        <%= submit_tag 'Search', class: 'btn search-btn'%>
        <% end %>
        <h4><u>Please note:</u> This is a demo page. <a href="mailto:support@querlatours.zendesk.com">Contact us</a> to get involved in building Querla!</h4>
      </div><!-- search-panel-wrapper -->
        
    </div><!-- row search-panel -->
  </div><!-- row header-panel -->

  
<!--   <div class='container-fluid'> -->
  
  <div class='row'>
    <div class="space"></div>
  </div>
  
  <div class="row ">
    <% @tours.each do |tour| %>
      <div class="col-md-4">
        <div class='thumbnail'>
        <a href="<%= tour_path(tour.id) %>"><%= image_tag(tour.tour_image.url(:square)) %>
          <div class='caption'>
            <h4><%= tour.name %></h4>
          </div>
        </div></a>
      </div>
		<% end %>
  </div> 
  </div>
    
  <div class = 'row info_bottom'> 
    <div class='row'></div>
    <div class='row'>
      <div class="col-md-3"></div>
      <div class="col-md-2">    
        <ul>
          <li><h4>Company</h4></li>
          <li><%= link_to "Become a Guide", welcome_guide_path %></li>
          <li><a href="https://querlatours.zendesk.com/hc/en-us">FAQ</a><li>
        </ul>
      </div>
      <div class="col-md-2">    
        <ul>
          <li><h4>Contact</h4></li>
          <li><address><a href="mailto:support@querlatours.zendesk.com">support@querlatours.zendesk.com</a></address></li>
        </ul>
      </div>
      <div class="col-md-2">    
        <ul>
          <li><h4>Address</h4></li>
          <li>Coming soon!</li>
        </ul>
      </div>
    </div>
    <div class= 'row'>
      <div class='col-md-3'></div>
      <div class='col-md-6'><hr></div>
      <div class='col-md-3'></div>
    </div>
   `<div class = 'row social-wrapper'> 
     <h4>Follow us on</h4>
      <div class="col-md-12">
        <a href="https://facebook.com/querlatours"><img alt= 'Facebook' src="/assets/social_facebook_cropped.png" height= '45' width='45'/></a>
        <a href="https://twitter.com/querlatours"><img alt= 'Twitter' src="/assets/social_twitter_cropped.png" height= '45' width='45'/></a>
        <a href="https://instagram.com/querlatours"><img alt= 'Instagram' src="/assets/social_instagram_cropped.png" height= '45' width='45'/></a>
    </div>
    </div>
    </div>
  