config/routes.rb
Rails.application.routes.draw do

  resources :calendar_requests

  resources :bookings
  
  resources :charges

  resources :calendars

  resources :tour_prices

  resources :tour_cities

  resources :tour_guides

  devise_for :users, :path_prefix => 'my', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  # This must go after devise_for to avoid conflicts
  
  resources :tickets
  
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/faq"
  get "welcome/admin"
  get "welcome/guide"
  
  resources :tours do 
    collection { post :import}
  end

  root to: 'welcome#index'
  
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :tour_guide
  belongs_to :tour_city
  belongs_to :tour_price
  has_many :calendars
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
 
  validates :name, presence: true, uniqueness: true
  validates :tour_image,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
 
  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:name, query) -> This would return an exact match of the query
    where('lower(name) like ?', "%#{query}%".downcase)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Tour.create! row.to_hash
    end
  end
  
  # This method associates the attribute ":tour_image" with a file attachment
  has_attached_file :tour_image, styles: {
    thumb: '100x100>',
    square: '420x420#',
    medium: '314x344#',
    long: '1390x344#'
  }
  
  
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  
  load_and_authorize_resource

  # GET /tours
  # GET /tours.json
  def index
    
    if params[:search_location].present?
      if params[:search].present?
        @tours = Tour.near(params[:search_location], 50).search(params[:search]).order("created_at DESC")
      else
        @tours = Tour.near(params[:search_location], 50)
      end
    elsif params[:search]
      @tours = Tour.search(params[:search]).order("created_at DESC")
    else
      @tours = Tour.all
    end
        
  end 

  # GET /tours/1
  # GET /tours/1.json
  def show
    @calendars = Calendar.where(tour_id: @tour.id).where("calendar_datetime >= :date", date: Date.today) 
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    @price_adult = Money.new(@tour.tour_price.price_adult*100, @tour.tour_price.currency).format
    @price_child = Money.new(@tour.tour_price.price_child*100, @tour.tour_price.currency).format
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
    flash[:alert] = "Please check that no bookings have been associated with this calendar listing before editing."
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    Tour.import(params[:file])
    redirect_to tours_path, notice: "Tours added successfully"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:created_at, :name, :short_description, :long_description, :tour_guide_id, :tour_city_id, :tour_price_id, :latitude, :longitude, :address, :meeting_point_description, :min_customer_threshold, :tour_image)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= bootstrap_form_for(@tour) do |f| %>

  <% if @tour.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

        <ul>
        <% @tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.text_field :name, placeholder: "Enter tour name" %>
  <%= f.text_field :short_description, placeholder: "Enter short description" %>
  <%= f.text_area :long_description, placeholder: "Enter long description" %>
  <%= f.collection_select :tour_guide_id, TourGuide.all, :id, :name %>
  <%= f.collection_select :tour_city_id, TourCity.all, :id, :city %>
  <%= f.text_field :meeting_point_description, placeholder: "Enter description of meeting place" %>
  <%= f.text_field :address, placeholder: "Enter address of meeting point" %>
  <%= f.text_field :latitude, placeholder: "This field will be automatically filled" %>
  <%= f.text_field :longitude, placeholder: "This field will be automatically filled" %>
  <%= f.collection_select :tour_price_id, TourPrice.all, :id, :name %>
  <%= f.number_field :min_customer_threshold, placeholder: "Min # of customers for tour" %>
  <%= f.file_field :tour_image %>

  <%= f.submit "Save" %>
<% end %>

  

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<div class='container'>
  <div class='row'>

    <h2>Tours</h2>
    <div class='pull-right range-query'>
      <div class='pull-left range-query search-bar'>
        <%= form_tag tours_path, method: :get, :class => "form-inline" do %>
        <div class='form-group'>
          <%= text_field_tag :search_location, params[:search_location], class: 'form-control', :placeholder => "Location" %>
        </div>
        <div class='form-group'>
          <%= text_field_tag :search, params[:search], class: 'form-control', :placeholder => "Interest" %>
        </div>
        <%= submit_tag 'Search', class: 'btn search-btn'%>
        <% end %>
      </div>
    </div>

  </div>

  <div class='media'>
    <div class='media-body'>

      <table class='table table-hover'>
        <thead>
          <tr>
            <th>Created at</th>
            <th>Name</th>
            <th>Short description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tours.each do |tour| %>
          <tr>
            <td><%= tour.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= tour.name %></td>
            <td><%= tour.short_description %></td>
            <td><%= link_to 'Show', tour, class: 'btn btn-mini' %></td>        
            <td><%= link_to 'Edit', edit_tour_path(tour), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', tour, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>

  <%= link_to 'New Tour', new_tour_path %>

</div>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<div class='container-fluid'>


  <div class = 'row tour-header'>
    <div class= 'tour-title'>
      <h1><%= @tour.name %></h1>
    </div>
    <div class="btn button_booknow">
      <h4>Book Now</h4>
    </div>
  </div>


   <div class='row'>
  <div class='tour-image'>
   <%= image_tag @tour.tour_image.url(:long), class: 'tour-image' %>
</div>
  </div>



  
  
<!--   <div class='row pad'>
  </div>

  <div class='row'>
      <div class="col-md-12">
        <%= image_tag @tour.tour_image.url(:long) %>
      </div>
  </div>
  <hr>
  
  <div class='row'>
      <div class='col-md-2'>
      </div>
      <div class='col-md-2'>
          <%= image_tag @tour.tour_guide.tour_guide_image.url(:thumb), class: 'img-circle' %>
          <br>
      </div>
      <div class="col-md-8">
          <h1><%= @tour.name %></h1>
        <% if user_signed_in? %>
            <%= link_to new_booking_path(:tour_id => @tour.id) do %>
                <div class="btn button_pink">
                    <h4>Book Now</h4>
                </div>
            <% end %>
        <% else %>
             <%= link_to  "#sign_up", "data-toggle" => "modal" do %>
                 <div class="btn button_pink">
                    <h4>Book Now</h4>
                 </div>
             <% end %>
        <% end %>
      </div>
  </div>
  <hr>
  
  <div class='row'>
      <div class="col-md-2">
           <h3>Description</h3>
       </div>
       <div class='col-md-10'>
          <%= @tour.long_description %>
       </div>
  </div>
  <hr>
  
  <div class='row'>
      <div class="col-md-2">
          <h3>Your Guide</h3>
       </div>
      <div class='col-md-10'>
         <%= @tour.tour_guide.description %>
      </div>
  </div>
  <hr>
  
  <div class='row'>
      <div class="col-md-2">
          <h3>Details</h3>
      </div>
      <div class='col-md-6'>
          <ul>
              <li>Duration: <%= @tour.tour_price.duration %> hour</li>
              <li>Meeting Place: <%= @tour.meeting_point_description %></li>
              <li>Address: <%= @tour.address %></li>
            <li><%= @price_adult %> Adults</li>
            <li><%= @price_child %> Children</li>
          </ul>
      </div>
      <div class='col-md-4'>
      </div>   
  </div>
  <hr>
  
  <div class='row'>
      <div class="col-md-2">
          <h3>Location</h3>
      </div>
      <div class='col-md-6'>
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@tour.latitude}%2C#{@tour.longitude}" %>
      </div>  
      <div class='col-md-4'>
      </div>  
  </div>
  <hr>

  
  <div class='row'>
      <div class="col-md-2">
          <h3>Dates</h3>
      </div>
      <div class='col-md-6'>
          <ul>
              <% @calendars.sort_by{|t| - t.calendar_datetime.to_i}[0..2].each do |calendar| %>
                  <% if user_signed_in? %>
                      <li><%= link_to (calendar.calendar_datetime.strftime(" %b-%d %Y at %I:%M%p")), new_booking_path(:tour_id => @tour.id, :calendar_id => calendar.id) %></li>
                  <% else %>
                      <li><%= link_to (calendar.calendar_datetime.strftime(" %b-%d %Y at %I:%M%p")), "#sign_up", "data-toggle" => "modal" %></li>
           
                  <% end %>
              <%end%>
          </ul>
      </div>  
      <div class='col-md-4'>
      </div>  
  </div>
  <hr>

  <div class='row'>
      <div class='col-md-2'>
          <h3>Calendar</h3>
      </div>
      <div class='col-md-10'>
          <div id='calendar'> 
              <h2 id='month'>
                <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
                <%=h @date.strftime("%B %Y")%>
                <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
              </h2>
              <%= calendar_for @calendars, :year => @date.year, :month => @date.month do |t| %>
              <%= t.head('Sun','Mon','Tues','Wed','Thurs','Fri','Sat') %>
              <%= t.day(:day_method => :calendar_datetime) do |date, calendars| %>
                    <%= date.day %>
                    <ul>
                      <% for calendar in calendars %>
                          <% if user_signed_in? %>
                            <li><%= link_to h(calendar.tour.name), new_booking_path(:tour_id => @tour.id, :calendar_id => calendar.id) %></li>
                          <% else %>
                            <li><%= link_to h(calendar.tour.name), new_user_registration_path %></li>
                          <% end %>
                      <%end%>
                    </ul>
                   <% end %>
              <% end %>
          </div>
      </div>
  </div>
  <hr>
  
  <div class='row'>
      <div class="col-md-2">
          <h3>Nearby Tours</h3>
      </div>
      <div class='col-md-6'>
          <ul>
          <% for tour in @tour.nearbys(5) %>
            <li><%= link_to tour.name, tour %> (<%= tour.distance.round(2) %> miles)</li>
          <% end %>
          </ul>
      </div>  
      <div class='col-md-4'>
      </div>  
  </div>
  <hr> -->



<!--  Admin Only -->
  
<% if can? :manage, @tour %>
<hr>
  
  <div class='row'>
    <div class='col-md-2'>
      <h3>Admin Only</h3>
    </div>
    <div class='col-md-10'>
      <ul>
        <li>Created at: <%= @tour.created_at %></li>
        <li>Meeting Point Latitude: <%= @tour.latitude %></li>
        <li>Meeting Point Longitude: <%= @tour.longitude %></li>
        <li>Tour Price Name: <%= @tour.tour_price.name %></li>
        <li>Min Customer Threshold: <%= @tour.min_customer_threshold %></li>
        <li>Tour City: <%= @tour.tour_city.city %></li>
      </ul>
    </div>
  </div>
  <hr>
  
  <%= link_to 'Edit', edit_tour_path(@tour) %>|
  <%= link_to 'Back', tours_path %>

<%end%>
  
</div>