config/routes.rb
Rails.application.routes.draw do

  resources :calendar_requests

  resources :bookings
  
  resources :charges

  resources :calendars

  resources :tour_prices

  resources :tour_cities

  resources :tour_guides

  devise_for :users, :path_prefix => 'my', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  # This must go after devise_for to avoid conflicts
  
  resources :tickets
  
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/faq"
  get "welcome/admin"
  get "welcome/guide"
  
  resources :tours do 
    collection { post :import}
  end

  root to: 'welcome#index'
  
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :tour
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  load_and_authorize_resource

  def index
    @calendars = Calendar.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    respond_with(@calendars)
  end

  def show
    respond_with(@calendar)
  end

  def new
    @calendar = Calendar.new
    respond_with(@calendar)
  end

  def edit
    flash[:alert] = "Please check that no bookings have been associated with this calendar listing before editing."
  end

  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.save
    respond_with(@calendar)
  end

  def update
    @calendar.update(calendar_params)
    respond_with(@calendar)
  end

  def destroy
    @calendar.destroy
    respond_with(@calendar)
  end

  private
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def calendar_params
      params.require(:calendar).permit(:calendar_datetime, :tour_id)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= bootstrap_form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.datetime_select :calendar_datetime %>
  <%= f.collection_select :tour_id, Tour.all, :id, :name %>
  <%= f.submit %>

<% end %>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<div class="container-fluid">
  <h2>Tour Calendar</h2>

  <%= link_to 'New Calendar Listing', new_calendar_path %>
  <br>

  <div id='calendar'> 
    <h2 id='month'>
      <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
      <%=h @date.strftime("%B %Y")%>
      <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
    </h2>
    <%= calendar_for @calendars, :year => @date.year, :month => @date.month do |t| %>
    <%= t.head('Sun','Mon','Tues','Wed','Thurs','Fri','Sat') %>
    <%= t.day(:day_method => :calendar_datetime) do |date, calendars| %>
          <%= date.day %>
          <ul>
            <% for calendar in calendars %>
              <li><%= link_to h(calendar.tour.name), calendar %></li>
            <%end%>
          </ul>
         <% end %>
    <% end %>
  </div>
  
  <br>
  
    <div class='media'>
    <div class='media-body'>
       <table class='table table-hover'>
          <thead>
            <tr>
              <th>DateTime</th>
              <th>Tour</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @calendars.each do |calendar| %>
              <tr>
                <td><%= calendar.calendar_datetime.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= calendar.tour.name %></td>
                <td><%= link_to 'Show', calendar, class: 'btn btn-mini' %></td>
                <td><%= link_to 'Edit', edit_calendar_path(calendar), class: 'btn btn-mini btn-success' %></td>
                <td><%= link_to 'Destroy', calendar, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Tour Calendar Listing</h1>
<p>
  <strong>DateTime:</strong>
  <%= @calendar.calendar_datetime %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @calendar.tour.name %>
</p>

<p>
  <strong>Tour Description:</strong>
  <%= @calendar.tour.short_description %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %>
<%= link_to 'Back', calendars_path %>