config/routes.rb
Rails.application.routes.draw do

  resources :calendar_requests

  resources :bookings
  
  resources :charges

  resources :calendars

  resources :tour_prices

  resources :tour_cities

  resources :tour_guides

  devise_for :users, :path_prefix => 'my', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  # This must go after devise_for to avoid conflicts
  
  resources :tickets
  
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/faq"
  get "welcome/admin"
  get "welcome/guide"
  
  resources :tours do 
    collection { post :import}
  end

  root to: 'welcome#index'
  
end

app/models/tour_guide.rb
class TourGuide < ActiveRecord::Base
  
    validates :tour_guide_image,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
  
    # This method associates the attribute ":tour_image" with a file attachment
    has_attached_file :tour_guide_image, styles: {
    thumb: '100x100#',
    square: '200x200#',
    medium: '300x300>'
  }
  
end

app/controllers/tour_guides_controller.rb
class TourGuidesController < ApplicationController
  before_action :set_tour_guide, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  load_and_authorize_resource

  def index
    @tour_guides = TourGuide.all
    respond_with(@tour_guides)
  end

  def show
    respond_with(@tour_guide)
  end

  def new
    @tour_guide = TourGuide.new
    respond_with(@tour_guide)
  end

  def edit
  end

  def create
    @tour_guide = TourGuide.new(tour_guide_params)
    @tour_guide.save
    respond_with(@tour_guide)
  end

  def update
    @tour_guide.update(tour_guide_params)
    respond_with(@tour_guide)
  end

  def destroy
    @tour_guide.destroy
    respond_with(@tour_guide)
  end

  private
    def set_tour_guide
      @tour_guide = TourGuide.find(params[:id])
    end

    def tour_guide_params
      params.require(:tour_guide).permit(:name, :description, :tour_guide_image)
    end
end

app/helpers/tour_guides_helper.rb
module TourGuidesHelper
end

app/views/tour_guides/_form.html.erb
<%= bootstrap_form_for(@tour_guide) do |f| %>

  <% if @tour_guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour_guide.errors.count, "error") %> prohibited this tour_guide from being saved:</h2>

      <ul>
      <% @tour_guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, placeholder: "Enter name of tour guide" %>
  <%= f.text_area :description, placeholder: "Enter description of tour guide" %>
  <%= f.file_field :tour_guide_image %>
  <%= f.submit %>

<% end %>

app/views/tour_guides/edit.html.erb
<h1>Editing tour_guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour_guide %> |
<%= link_to 'Back', tour_guides_path %>

app/views/tour_guides/index.html.erb
<div class='container'>
  <h2>Tour Guides</h2>


  <div class='media'>
    <div class='media-body'>

      <table class='table table-hover'>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tour_guides.each do |tour_guide| %>
          <tr>
            <td><%= tour_guide.name %></td>
            <td><%= tour_guide.description %></td>
            <td><%= link_to 'Show', tour_guide, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_tour_guide_path(tour_guide), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', tour_guide, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>

  <br>

  <%= link_to 'New Tour guide', new_tour_guide_path %>
</div>

app/views/tour_guides/new.html.erb
<h1>New tour_guide</h1>

<%= render 'form' %>

<%= link_to 'Back', tour_guides_path %>

app/views/tour_guides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour_guide.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour_guide.description %>
</p>

<p>
  <%= image_tag @tour_guide.tour_guide_image.url(:square) %>
</p>

<%= link_to 'Edit', edit_tour_guide_path(@tour_guide) %> |
<%= link_to 'Back', tour_guides_path %>